"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CricketCoach_1 = require("./CricketCoach");
var HappyFortuneService_1 = require("./HappyFortuneService");
var SadFortuneService_1 = require("./SadFortuneService");
var SwimmingCoach_1 = require("./SwimmingCoach");
var myCoach;
var fortueService;
fortueService = new HappyFortuneService_1.HappyFortuneService();
myCoach = new CricketCoach_1.CricketCoach(fortueService);
console.log(myCoach.getDailyWorkout());
console.log(myCoach.getDailyFortune());
fortueService = new SadFortuneService_1.SadFortuneService();
myCoach = new SwimmingCoach_1.SwimmingCoach(fortueService);
console.log(myCoach.getDailyWorkout());
console.log(myCoach.getDailyFortune());
